### ISSUE TITLE
`AIRFLOW__CORE__XCOM_BACKEND` can't find modules

### ISSUE THREAD

**Issue by rightx2** [airflow-helm/charts#245]
**What is the bug?**
I tried to set `AIRFLOW__CORE__XCOM_BACKEND` with my custom xcom backend, `plugins.xcom_backend.S3XComBackend` but when I upgraded helm release, it couldn't find out the modules(workers keep dying)
So I set `PYTHONPATH` so that it could find `plugins` module but it still couldn't find out the module either.
It looks like loading `plugins.xcom_backend.S3XComBackend` had been executed before `PYTHONPATH` was defined.  

The directory structure in the cluster (`tree /opt/airflow/dags/repo`):
```
|- README.md
|- requirements.txt
|- tests
|- dags
|- plugins
    |- xcom_backend.py
```
How can I handle this problem?

**What version of the chart are you using?**:

I am using version `8.1.3`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```

**Please copy your custom Helm values file:**

```yaml
airflow:
  extraEnv:
    - name: PYTHONPATH
      value: "/opt/airflow/dags/repo"

  config: 
    AIRFLOW__CORE__XCOM_BACKEND: "plugins.xcom_backend.S3XComBackend"

```

**Comment by thesuperzapper** [comment]
@rightx2 can you post logs from the workers which die?

**Comment by rightx2** [comment]
@thesuperzapper 
```
 ➜ kubectl logs -p airflow-worker-0 -c check-db
[2021-06-30 05:36:06,520] {configuration.py:459} ERROR - No module named 'plugins'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py", line 457, in getimport
    return import_string(full_qualified_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 47, in command
    func = import_string(import_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/db_command.py", line 24, in <module>
    from airflow.utils import cli as cli_utils, db
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/db.py", line 26, in <module>
    from airflow.jobs.base_job import BaseJob  # noqa: F401 # pylint: disable=unused-import
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/__init__.py", line 19, in <module>
    import airflow.jobs.backfill_job  # noqa
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/backfill_job.py", line 29, in <module>
    from airflow import models
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/__init__.py", line 20, in <module>
    from airflow.models.baseoperator import BaseOperator, BaseOperatorLink
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 55, in <module>
    from airflow.models.taskinstance import Context, TaskInstance, clear_task_instances
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 58, in <module>
    from airflow.models.xcom import XCOM_RETURN_KEY, XCom
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 289, in <module>
    XCom = resolve_xcom_backend()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 279, in resolve_xcom_backend
    clazz = conf.getimport("core", "xcom_backend", fallback=f"airflow.models.xcom.{BaseXCom.__name__}")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py", line 460, in getimport
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "xcom_backend" key in "core" section. Current value: "plugins.xcom_backend.S3XComBackend".
```

**Comment by thesuperzapper** [comment]
@rightx2 have you got an`__init__.py` file in your `plugins` folder?

**Comment by rightx2** [comment]
@thesuperzapper Yes, of course. Moreover, I checked that `PYTHONPATH` is set properly when I didn't set `AIRFLOW__CORE__XCOM_BACKEND: "plugins.xcom_backend.S3XComBackend"`. I think that airflow configuration setting runs first before `PYTHONPATH` is declared.....

**Comment by thesuperzapper** [comment]
@rightx2 this is a fun issue, thanks for raising it, I might not have noticed.

I believe the issue is caused by volumes not being mounted on init-containers, and have raised an issue to track that: https://github.com/airflow-helm/charts/issues/253

I am currently working on a PR to fix this, hopefully finished very soon.

**Comment by thesuperzapper** [comment]
@rightx2 I have raised PR: https://github.com/airflow-helm/charts/pull/255 to fix this

**Comment by thesuperzapper** [comment]
@rightx2 can you confirm if [version 8.4.0](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#840---2021-07-09) has resolved this issue for you?

**Comment by tyg03485** [comment]
Hi, I'm @rightx2 's teammate.

At first, The reason for this issue is that airflow config has xcom settings, but the actual related file cannot be found in the dag volume mount location.
The initial chart probably did not support init-container and job separately because mostly they don't need dag volume.
**Anyway, It was solved as just attaching the `AIRFLOW__CORE__XCOM_BACKEND` environment variables on only the worker and scheduler.**

FYI. It's was not solved as PR, adding `extraVolumes`, `extraVolumeMounts`. Because, In init-container they can't communicate data with volume mount even if the order is correct. (I don't know why they can't communicate data in init-container)

**Comment by thesuperzapper** [comment]
@tyg03485 are you sure that this issue was not solved after version `8.4.0`

The `8.4.0` version included PR https://github.com/airflow-helm/charts/pull/255, which made sure that init-containers mounted `extraVolumes`, `extraVolumeMounts`, and git-sync's `dags-data` volume.

**Comment by tyg03485** [comment]
Yes, I also tested on `8.4.0` and It didn't work. `check-db` init-container is problem which i said above.

**Comment by tyg03485** [comment]
Maybe you can check it with below override value
```yaml
...
airflow:
  extraEnv:
    - name: PYTHONPATH
      value: {{ PYTHON PATH }}
    - name: AIRFLOW__CORE__XCOM_BACKEND
      value: plugins.xcom_backend.S3XComBackend
...
```

**Comment by thesuperzapper** [comment]
@tyg03485 can you share a version of your plugin so I can test it on my end?

**Comment by thesuperzapper** [comment]
@rightx2 I believe that this should be resolved in version `8.5.0` of the chart, can you verify this?

**Comment by v-lohana** [comment]
What is final solution to this ? because I am still facing it.

**Comment by thesuperzapper** [comment]
@v-lohana this is quite an old issue, what version of the chart are you running, and can you clarify the exact problem you are experiencing (preferably with logs)?
