### ISSUE TITLE
airflow-pgbouncer pod failing liveness probe on initialization when pgbouncer is enabled

### ISSUE THREAD

**Issue by TAMQuiroz** [airflow-helm/charts#394]
**What is the bug?**

I'm experimenting with the 8.5.0 chart version and when I'm installing with Pgbouncer feature disabled, everything works as usual but activating Pgbouncer flag on values.yaml, I get an error on the airflow-pgbouncer pod liveness probe:

```console
Liveness probe failed: psql: error: invalid integer value "POSTGRESPASSWORD@airflow-pgbouncer.airflow.svc.cluster.local:6432" for connection option "port"
```

And the other pods don't initialize either due to DB connection issue, I'm assuming is because Pgbouncer pod doesn't initialize.

**What version of the chart are you using?**:

I am using version `8.5.0`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"1af681ff123a96cc50f4f6323a83c70a1daf6950", GitTreeState:"clean", BuildDate:"2021-05-25T17:37:16Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

**Please copy your custom Helm values file:**

I'm using the default Pgbouncer config from the repo, haven't modified the file as I didn't saw any config that needed to be changed, if I'm wrong please let me know.

Thank you.

**Comment by thesuperzapper** [comment]
@TAMQuiroz @harscoet

You must have an `@` symbol in your `externalDatabase.user` value, probably because you are using Azure PostgreSQL, if so, you will need to encode it as `%40`:
```yaml
externalDatabase:
  # for `me@example.com`
  user: me%40example.com
```

---

I have raised issue https://github.com/airflow-helm/charts/issues/318 to automatically URL encode symbols like `@` in `externalDatabase.user`, and I plan to resolve it in `8.6.0`.

__WARNING:__ you will probably need to change your `%40` back into an `@` after `8.6.0`, but for now you can just encode it manually with `%40`.

**Comment by TAMQuiroz** [comment]
@thesuperzapper 

Yes, I'm using a Azure Postgres server and DB. I encoded the username to use `%40` as a test and now I get a different error concerning the password:

![image](https://user-images.githubusercontent.com/10441155/130496963-28a76208-e7a6-43dc-a66b-b86f38155ce5.png)

I really doubt my password is wrong as it works if I disable PGBouncer or try to connect myself directly to the server.

**Comment by thesuperzapper** [comment]
@TAMQuiroz I believe it's currently __not possible__ to use the pgbouncer when you manually URL encode your username, so I have raised issue https://github.com/airflow-helm/charts/issues/401 to get this resolved ASAP.

Expect it fixed in the next release.

**Comment by TAMQuiroz** [comment]
@thesuperzapper 

I'm testing chart v8.5.2 and I no longer have the issue stated on this bug but the liveness probe is still failing with message:

`Liveness probe failed: psql: error: ERROR: password authentication failed for user "[USERNAME]"`

I'm using Azure for Postgres, and as you know, the username has an @ in the middle of the value but the log only shows the value before the @. I'm guessing this is why the auth is failing.

Using `pgbouncer.serverSSL.mode: verify-ca` and default values.

The pod logs show this:
![image](https://user-images.githubusercontent.com/10441155/130823698-4e43b210-d835-4ef3-bc3b-493d942b044c.png)

Is this a PgBouncer issue or related to the Azure username problems?

Thank you for your efforts!
